
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Set;
import java.util.HashSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author naiks
 */
public class JewellerySuplied extends javax.swing.JFrame {
    private int vendorPk =0;
    private int jewsupPk =0;
    private int jewelleryPk=0;
     private Set<Integer> usedIds = new HashSet<>();
    // Initialize a counter for generating unique IDs
    private int jewelleryIdCounter = 1;
    
    /**
     * Creates new form JewellerySuplied
     */
    public JewellerySuplied() {
        initComponents();
        setLocationRelativeTo(null);
        populateJewelleryModel();
    }
    
    private void populateJewelleryModel() {
        DefaultTableModel jewelleryModel = (DefaultTableModel) tablejewellerysupplied.getModel();
        jewelleryModel.setRowCount(0); // Clear existing rows
        
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM jewellerysuplied");
            while (rs.next()) {
                jewelleryModel.addRow(new Object[]{
                    rs.getString("jewsup_pk"),
                    rs.getString("v_name"),
                    rs.getString("v_phonenumber"),
                    rs.getString("name"),
                    rs.getString("description"),
                    rs.getString("quantity"),
                    rs.getString("price"),
                });
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
     private String generateUniqueJewelleryId() {
        // Generate a unique ID based on the current count
        int jewelleryId;
        do {
            jewelleryId = jewelleryIdCounter++;
        } while (usedIds.contains(jewelleryId)); // Check if the ID has been used before

        // Add the generated ID to the set of used IDs
        usedIds.add(jewelleryId);

        return String.valueOf(jewelleryId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevendor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablejewellery = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablejewellerysupplied = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVendorPhoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtjname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtjdescription = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtjquantity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtjprice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnrReset = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablevendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Number"
            }
        ));
        tablevendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablevendorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablevendor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 119, 320, 256));

        tablejewellery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Quantity", "Price"
            }
        ));
        tablejewellery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablejewelleryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablejewellery);
        if (tablejewellery.getColumnModel().getColumnCount() > 0) {
            tablejewellery.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 119, 475, 256));

        tablejewellerysupplied.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "V_Name", "V-PhoneNumber", "Name", "Description", "Quantity", "Price"
            }
        ));
        jScrollPane3.setViewportView(tablejewellerysupplied);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 423, 845, 331));

        jLabel3.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jewellery Supplied");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 9, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Vendor List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 81, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jewellery List");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Supplied Jewellery");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Selected Vendor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 119, -1, 16));

        txtVendorName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVendorName.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 194, 413, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PhoneNumber");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 234, -1, -1));

        txtVendorPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVendorPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtVendorPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 268, 413, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jewellery");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 355, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 393, -1, -1));

        txtjname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjname.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtjname, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 415, 413, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Description");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 464, -1, -1));

        txtjdescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjdescription.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtjdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 486, 413, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Quantity");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 526, -1, -1));

        txtjquantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjquantity.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtjquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 548, 413, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 588, -1, -1));

        txtjprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjprice.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtjprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 616, 413, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 680, 410, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 314, 413, -1));

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        btnrReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnrReset.setForeground(new java.awt.Color(0, 0, 0));
        btnrReset.setText("Reset");
        btnrReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnrReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 731, 410, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order Bg.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtVendorName.setEditable(false);
        txtVendorPhoneNumber.setEditable(false);
        
        txtjname.setEditable(false);
        txtjdescription.setEditable(false);
        txtjquantity.setEditable(false);
        txtjprice.setEditable(false);
        
        
        DefaultTableModel vendormodel = (DefaultTableModel) tablevendor.getModel();
        DefaultTableModel model = (DefaultTableModel) tablejewellery.getModel();
        try{
           Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from vendor");
            while (rs.next()) {
                vendormodel.addRow(new Object[]{rs.getString("vendor_pk"),rs.getString("name"), rs.getString("phonenumber")}); 
        }
            rs = st.executeQuery("select * from jewellerydetails");
             while (rs.next()) {
                model.addRow(new Object[]{rs.getString("jewellery_pk"),rs.getString("name"), rs.getString("description"),rs.getString("quantity"),rs.getString("price")});
            }
        }
        catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int rowIndex = tablejewellerysupplied.getSelectedRow();
        if (rowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Please select a record to delete.");
            return;
        }
        String jewelleryId = tablejewellerysupplied.getValueAt(rowIndex, 0).toString();
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("DELETE FROM jewellerysuplied WHERE jewsup_pk = ?");
            ps.setString(1, jewelleryId);
            int deletedRows = ps.executeUpdate();
            if (deletedRows > 0) {
                JOptionPane.showMessageDialog(null, "JewellerySupply Details deleted successfully.");
           
                DefaultTableModel model = (DefaultTableModel) tablejewellerysupplied.getModel();
                model.removeRow(rowIndex);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete employee.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tablevendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablevendorMouseClicked
        // TODO add your handling code here:
        int index = tablevendor.getSelectedRow();
        TableModel model = tablevendor.getModel();
        String id = model.getValueAt(index, 0).toString();
        vendorPk =Integer.parseInt(id);
     
        String cname = model.getValueAt(index, 1).toString();
        txtVendorName.setText(cname);

        String cphoneNumber = model.getValueAt(index, 2).toString();
        txtVendorPhoneNumber.setText(cphoneNumber);
    }//GEN-LAST:event_tablevendorMouseClicked

    private void tablejewelleryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablejewelleryMouseClicked
        // TODO add your handling code here:
        int index = tablejewellery.getSelectedRow();
        TableModel model = tablejewellery.getModel();
        String id = model.getValueAt(index, 0).toString();
        jewelleryPk =Integer.parseInt(id);
     
        String name = model.getValueAt(index, 1).toString();
        txtjname.setText(name);

        String description = model.getValueAt(index, 2).toString();
        txtjdescription.setText(description);
        
        String quantity = model.getValueAt(index, 3).toString();
        txtjquantity.setText(quantity);
        
        String price = model.getValueAt(index, 4).toString();
        txtjprice.setText(price);
    }//GEN-LAST:event_tablejewelleryMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String name = txtVendorName.getText();
    String phoneNumber = txtVendorPhoneNumber.getText();
    String jname = txtjname.getText();
    String jdescription = txtjdescription.getText();
    String jquantity = txtjquantity.getText();
    String jPrice = txtjprice.getText();
    String jewelleryId = generateUniqueJewelleryId();
    
    if (name.isEmpty() || phoneNumber.isEmpty() || jname.isEmpty() || jPrice.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        return;
    }
    
    boolean jewelleryAlreadyPurchased = false;
    DefaultTableModel jewelleryModel = (DefaultTableModel) tablejewellerysupplied.getModel();
    for (int i = 0; i < jewelleryModel.getRowCount(); i++) {
        String existingJName = (String) jewelleryModel.getValueAt(i, 3);
        if (jname.equalsIgnoreCase(existingJName)) {
            jewelleryAlreadyPurchased = true;
            break;
        }
    }
    
    if (jewelleryAlreadyPurchased) {
        JOptionPane.showMessageDialog(this, "Jewellery item already purchased.");
    } else {
        try (Connection con = ConnectionProvider.getCon()) {
            PreparedStatement ps = con.prepareStatement("INSERT INTO jewellerysuplied (jewsup_pk, v_name, v_phonenumber, name, description, quantity, price) VALUES (?, ?, ?, ?, ?, ?, ?)");

            ps.setString(1, jewelleryId);
            ps.setString(2, name);
            ps.setString(3, phoneNumber);
            ps.setString(4, jname);
            ps.setString(5, jdescription);
            ps.setString(6, jquantity);
            ps.setString(7, jPrice);

            ps.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inserting data into the database: " + e.getMessage());
            e.printStackTrace(); // Print the stack trace for debugging purposes
            return;
        }

        jewelleryModel.addRow(new Object[]{jewelleryId, name, phoneNumber, jname, jdescription, jquantity, jPrice});
        jewelleryModel.fireTableDataChanged();
    }  
           
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnrResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new JewellerySuplied().setVisible(true);
    }//GEN-LAST:event_btnrResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For detils see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JewellerySuplied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JewellerySuplied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JewellerySuplied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JewellerySuplied.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JewellerySuplied().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnrReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablejewellery;
    private javax.swing.JTable tablejewellerysupplied;
    private javax.swing.JTable tablevendor;
    private javax.swing.JTextField txtVendorName;
    private javax.swing.JTextField txtVendorPhoneNumber;
    private javax.swing.JTextField txtjdescription;
    private javax.swing.JTextField txtjname;
    private javax.swing.JTextField txtjprice;
    private javax.swing.JTextField txtjquantity;
    // End of variables declaration//GEN-END:variables
}
